### PR TITLE
Rust upgrade

### PR DESCRIPTION
**Pull request by zimbatm**
I tried compiling the lib with rust 1.8 and had to update some of the dependencies. One thing leading to another and I was touching a bit more code. Here is an overview of things that changed:
- queryst is now replaced by the url crate
- the authenticate_ methods now take a channel_name and socket_id. Applications would want to know what channel they are authorising.

There are some errors in the test suite because the mocking has changed signature, not really sure what to do about this.

### CODE REVIEW

**Comment by WillSewell** [comment]
@zimbatm @jpatel531 let me know if know if I've done any disgraces since this is my first time writing rust. In particular in the way the auth string is built in `src/request_url.rs`.

**Comment by jpatel531** [comment]
hahah @WillSewell - i've probably committed lots of rust disgraces. go for it!

**Comment by jpatel531** [comment]
i wonder if there's a better way to build unescaped query strings? but yolo, LGTM

**Comment by WillSewell** [comment]
I did look into it for a little while, but couldn't find an obvious way of doing it using the current libraries.

Might just YOLO.

**Comment by WillSewell** [comment]
@jpatel531 any chance you can give me access to https://crates.io/crates/pusher ?

**Pull request merged**
