### PR TITLE
Remove mutable reference requirement

### LINKED ISSUE #12: Don't require a mutable reference to trigger pusher events
Currently the `trigger` methods require a `&mut self`, but there's no reason to require that, since the pusher client is not stateful.

The underlying `Client` only requires an immutable reference to send requests.

### PR DESCRIPTION
**Pull request by kayleg**
Since the underlying client doesn't need to be `mut` requiring the `&mut` complicates the usage of having a single Pusher client in a more complex program.
 
This PR closes #12 by removing the `mut` requirement.

Additionally, `rustfmt` was executed on the changed files in order to match the rust recommended style guidelines.

### CODE REVIEW

**Comment by WillSewell** [comment]
Thank you for submitting this PR! I certainly think it's a good idea.

However it's currently quite hard to review with the `rustfmt` changes mixed in. I'm in favour of running `rustfmt` against this repo, but I think it should be done in a separate commit, or ideally a separate PR. And it should be run against the whole repo at once. Would you be able to do that please?

**Comment by kayleg** [comment]
Yeah, no problem. I will undo the formatting and create a separate PR for `rustfmt`

**Comment by kayleg** [comment]
@WillSewell The `rustfmt` changes have been reverted so this is purely the removal of the mutable reference now.

**Review by WillSewell — CHANGES_REQUESTED** [review]
This looks good! Just one doc I noticed needs updating still, in the `src/lib.rs` file

Am I correct in thinking these changes are backwards compatible? I believe they are, but I'd like to double check.

**Comment by kayleg** [comment]
I updated the doc to reflect the non-mut.
(Note: That example in `src/lib.rs` seems to be out of date with the `async/await` changes. It compiles but doesn't do anything since the future isn't polled).

Yes, this is backwards compatible as `&mut` is a stronger guarantee than `&` so it should downgrade without problem. It will cause a few lint messages that the `mut` is not required.

**Review by WillSewell — APPROVED** [review]
Looks good! Thank you for doing this :)

Thanks for pointing out the example being out of date. I added an issue as a reminder: https://github.com/pusher-community/pusher-http-rust/issues/22.

**Pull request merged**
